import { WORKSPACE_CONFIG_FILENAME, FLOW_BOOK_DIRNAME } from './config-filenames.js'
import { gameDemoScaffold, gameDemoWorkspaceConfig } from '../demoBooks/game-demo-scaffold.js'

// NOTE: packages/create-flowkit-app/index.js's write*Screen/writeDb/writeFlowStories
// functions hand-port this same demo content for standalone publishing (it can't
// import this file — see that file's own top-of-file comment on why). If you add
// or remove a demo page/chapter here, update it there too — both this file and
// workspace-template.js pull demo content from the single shared
// scripts/demoBooks/game-demo-scaffold.js module, so there is only one place to
// change; only manifest.ts's own config differs (mode-correct defineConfig
// import line).
// scripts/tests/scaffold-consistency.test.js checks structural shape (page/chapter
// counts), not full content or exact ids.
export function workspaceScaffold(name, kit = 'none', isStandalone = false, empty = false) {
  const kitCssImport =
    kit === 'none'
      ? ''
      : isStandalone
        ? `@import "@flowkit/kits/standalone/${kit}/index.css";`
        : `@import "@flowkit-kit/index.css";`

  const tokensCss =
    kit === 'none'
      ? `/* ${name} — Design Tokens */\n/* No kit selected — add your own CSS variables here. */\n:root {\n  /* --my-brand: #1a1a2e; */\n}\n`
      : isStandalone
        ? `/* ${name} — Design Tokens */\n/* Standalone kit: ${kit} — self-contained cascade, no shared components */\n${kitCssImport}\n\n/* ── Workspace-level overrides ─────────────────────────────────────────────\n   Override kit variables under [data-kit="${kit}"] here.\n   ────────────────────────────────────────────────────────────────────────── */\n[data-kit="${kit}"] {\n  /* --wf-font: "Inter", system-ui, sans-serif; */\n}\n`
        : `/* ${name} — Design Tokens */\n/* Kit base + theme + utilities — imported first; overrides below */\n${kitCssImport}\n\n/* ── Workspace-level overrides ─────────────────────────────────────────────\n   Override any --kit-* variable here to customise the active theme.\n   These always win over theme defaults (last write in cascade).\n   ────────────────────────────────────────────────────────────────────────── */\n:root {\n  /* --kit-brand: #1a1a2e; */\n  /* --kit-font:  "Inter", system-ui, sans-serif; */\n}\n`

  return empty
    ? emptyWorkspaceScaffoldFiles(name, tokensCss)
    : workspaceScaffoldFiles(name, tokensCss)
}

/** Bare, essential-only scaffold — no demo chapters/pages/flowStories/components.
 * Used by --empty. Still a fully valid, buildable workspace: config declares
 * zero chapters (an author's first `flowkit create:chapter` populates it), db
 * and simulator are empty stubs, no flowStories directory (no chapters to
 * reference yet — `flowkit create:flowStory` creates it on demand). */
function emptyWorkspaceScaffoldFiles(name, tokensCss) {
  return {
    'index.ts': `// Workspace barrel — add shared exports here as needed.\n// The platform reads pages via the ${FLOW_BOOK_DIRNAME}/ glob; no router required.\n`,
    'lib/data/db.ts': `// Workspace mock database — all runtime state lives here.\n// Named exports are loaded into the platform db object on startup.\n\nexport const user = {\n  name: 'Demo User',\n}\n`,
    'lib/data/simulator.tsx': `import { ControlAccordion, SimAction } from '@flowkit-features/simulator/controls'\n\nexport default function WorkspaceSimulatorControls() {\n  return (\n    <ControlAccordion label="Data" defaultOpen>\n      <SimAction label="Reset Database" icon="Trash2" badgeColor="red" onClick={ctx => ctx.resetDb()} />\n    </ControlAccordion>\n  )\n}\n`,
    'lib/design-system/tokens.css': tokensCss,
    [WORKSPACE_CONFIG_FILENAME]: `import { defineConfig } from '@flowkit-core/config'\n\nexport default defineConfig({\n  workspace: { name: '${name}' },\n  chapters: [],\n  pageOrder: {},\n})\n`,
    '.flowkit/components.json': `[]\n`,
    'lib/docs/overview.md': `# ${name} — Project Overview\n\n## What this is\n<!-- Describe the product and its purpose -->\n\n## Platform\n- **Target OS:** iOS / Android\n- **Primary device:** iPhone 16 Pro (393×852)\n- **Form factor:** Phone-first\n\n## Scaffold commands\n\`\`\`\nflowkit create:chapter --name:<chapter>\nflowkit create:page --chapter:<chapter> --name:<page>\nflowkit create:flowStory --name:<id>\nflowkit create:component --name:<Name> --path:lib/components/ui\n\`\`\`\n`,
  }
}

function workspaceScaffoldFiles(name, tokensCss) {
  return {
    [WORKSPACE_CONFIG_FILENAME]: gameDemoWorkspaceConfig(name),
    ...gameDemoScaffold(name, tokensCss + '\n'),
    // NOTE: .agent/* files (INDEX, rules, platform) + the chosen agent's memory
    // file (CLAUDE.md / AGENTS.md / .cursor/rules) + project.md are generated by
    // scripts/platform/agent-sync.js from the single-source spec (agent-spec.js),
    // written by cmdNewWorkspace after this scaffold. Keep them OUT of this map
    // so there's one source of truth and `flowkit agent:sync` can re-emit them.
  }
}
